// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Cate struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Post struct {
	ID        int64         `json:"id"`
	CateID    sql.NullInt32 `json:"cate_id"`
	UserID    sql.NullInt32 `json:"user_id"`
	Title     string        `json:"title"`
	Content   string        `json:"content"`
	CreatedAt time.Time     `json:"created_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Username  sql.NullString `json:"username"`
	Password  string         `json:"password"`
	CreatedAt time.Time      `json:"created_at"`
}
