// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateCate(ctx context.Context, arg CreateCateParams) (Cate, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error)
	GetCate(ctx context.Context, id int32) (Cate, error)
	GetPosts(ctx context.Context, id int32) (Post, error)
	GetUser(ctx context.Context, id int32) (User, error)
	ListCates(ctx context.Context, arg ListCatesParams) ([]Cate, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
}

var _ Querier = (*Queries)(nil)
